ffmpeg -i bubble.wav bubble.wav.mp3
ffmpeg -i cold.wav cold.wav.mp3
ffmpeg -i colder.wav colder.wav.mp3
ffmpeg -i h5_tune_swipe.wav h5_tune_swipe.wav.mp3
ffmpeg -i h_12_f_10_s_t.wav h_12_f_10_s_t.wav.mp3
ffmpeg -i h_5_f_2_s_f.wav h_5_f_2_s_f.wav.mp3
ffmpeg -i h_6_f_10_s_f.wav h_6_f_10_s_f.wav.mp3
ffmpeg -i h_6_f_10_s_t.wav h_6_f_10_s_t.wav.mp3
ffmpeg -i steel.wav steel.wav.mp3
